title: Hold My Grog
description: A space for mod and connection info if interested in joining our gaming servers.

url: http://holdmygrog.net
baseurl: "/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: holdmygrog
  twitter: holdmygrog_net
  facebook: holdmygrog
  email: holdmygrog.net@gmail.com
  linkedin: holdmygrog

google_analytics: "UA-58263416-1"

disqus:
    shortname: terryt
